### ISSUE TITLE
Setting require.extensions overwrites hook installed by pirates.

### ISSUE THREAD

**Issue by coreyfarrell** [danez/pirates#57]
I was looking into switching nyc from append-transform to pirates but ran into an issue.  One of the nyc tests verifies that instrumentation still works when someone sets `require.extensions['.js']` after nyc installs the require hook.  This test determined that setting `require.extensions['.js'] = hookFunction` removes the hook installed by pirates.  Is this intentional or would you be open to addressing this?

**Comment by danez** [comment]
I know this is an old issue, but I don't see how this could be fixed. pirates basically does `require.extensions['.js'] = hookFunction` internally, and I do not see how we could prevent someone overwriting it afterwards.
I would totally be open to fixing this but have no idea how.
